steps:
# Step 1
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
   '-c',
   'docker pull gcr.io/$PROJECT_ID/connectivity:$SHORT_SHA || exit 0'
  ]
# Step 2
- name: gcr.io/cloud-builders/docker
  args: [
   'build',
   '-t',
   'gcr.io/$PROJECT_ID/connectivity:$SHORT_SHA',
   '.'
  ]
  dir: 'connectivity'
# Step 3
- id: scan
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: /bin/bash
  args:
  - -c
  - |
    gcloud artifacts docker images scan gcr.io/$PROJECT_ID/connectivity:$SHORT_SHA \
    --format='value(response.scan)' > /workspace/scan_id.txt
# Step 4
- id: severity check
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: /bin/bash
  args:
  - -c
  - |
    gcloud artifacts docker images list-vulnerabilities $(cat /workspace/scan_id.txt) \
    --format='value(vulnerability.effectiveSeverity)' | if grep -Fxq $_SEVERITY; \
    then echo 'Failed vulnerability check' && exit 1; else exit 0; fi
